// One-time AI enrichment: a concise, factual title + description per place,
// generated by Claude Haiku and cached in place_geo. Our own content.

import Anthropic from "@anthropic-ai/sdk";
import { kindLabel } from "./format.mjs";

const MODEL = "claude-haiku-4-5";

const SCHEMA = {
  type: "object",
  properties: {
    title: { type: "string", description: "Short display title, <= 60 chars" },
    description: { type: "string", description: "1–2 plain sentences, <= 240 chars" },
  },
  required: ["title", "description"],
  additionalProperties: false,
};

const SYSTEM =
  "You write concise, factual directory entries for a UK motorhome & campervan " +
  "stopover and facilities website. British English. No marketing fluff, no emoji, " +
  "and never invent facts not present in the input. Title: a clean name (<=60 chars). " +
  "Description: 1–2 plain sentences (<=240 chars) covering what it is and any useful " +
  "facilities. If little is known, keep it short and generic.";

// Build a compact context string from a place row + parsed OSM tags + og text.
function contextFor(p, tags, ogDesc) {
  const pick = (k) => tags[k];
  const lines = [
    `Type: ${kindLabel(p.category)}`,
    p.name ? `Name: ${p.name}` : null,
    pick("operator") ? `Operator: ${pick("operator")}` : null,
    pick("addr:city") || pick("addr:town") ? `Town: ${pick("addr:city") || pick("addr:town")}` : null,
    pick("addr:postcode") ? `Postcode: ${pick("addr:postcode")}` : null,
    pick("description") ? `OSM description: ${pick("description")}` : null,
    pick("opening_hours") ? `Opening hours: ${pick("opening_hours")}` : null,
    pick("fee") ? `Fee: ${pick("fee")}` : null,
    p.has_water ? "Has drinking water" : null,
    p.has_dump ? "Has waste/Elsan disposal" : null,
    p.has_toilets ? "Has toilets" : null,
    ogDesc ? `Website summary: ${ogDesc}` : null,
  ].filter(Boolean);
  return lines.join("\n");
}

async function generate(client, context) {
  const res = await client.messages.create({
    model: MODEL,
    max_tokens: 400,
    system: SYSTEM,
    output_config: { format: { type: "json_schema", schema: SCHEMA } },
    messages: [{ role: "user", content: context }],
  });
  const text = res.content.find((b) => b.type === "text")?.text || "{}";
  const j = JSON.parse(text);
  return { title: (j.title || "").slice(0, 80), desc: (j.description || "").slice(0, 300) };
}

// Enrich a batch of OSM places that haven't been AI-enriched yet.
export async function enrichBatch(env, limit = 10) {
  if (!env.ANTHROPIC_API_KEY) return { processed: 0, ok: 0, error: "no ANTHROPIC_API_KEY" };
  const client = new Anthropic({ apiKey: env.ANTHROPIC_API_KEY });

  const pending = await env.DB.prepare(
    `SELECT o.osm_id, o.name, o.category, o.has_water, o.has_dump, o.has_toilets, o.tags,` +
      ` g.og_desc FROM osm_places o` +
      ` LEFT JOIN place_geo g ON g.place_ref = 'osm/' || o.osm_id` +
      // Only the stopover/site categories — water/dump/toilets are self-describing.
      ` WHERE o.category IN ('caravan_site','camp_site','motorhome_parking')` +
      ` AND g.ai_checked IS NULL LIMIT ?`
  ).bind(limit).all();

  const now = new Date().toISOString();
  let ok = 0;
  await Promise.all(
    pending.results.map(async (r) => {
      const ref = `osm/${r.osm_id}`;
      let tags = {};
      try { tags = r.tags ? JSON.parse(r.tags) : {}; } catch {}
      let title = null, desc = null;
      try {
        const out = await generate(client, contextFor(r, tags, r.og_desc));
        title = out.title || null;
        desc = out.desc || null;
        if (desc) ok++;
      } catch (e) {
        // leave null; still stamp ai_checked so we don't loop forever
      }
      await env.DB.prepare(
        `INSERT INTO place_geo (place_ref, ai_title, ai_desc, ai_checked, cached_at)` +
          ` VALUES (?, ?, ?, ?, ?)` +
          ` ON CONFLICT(place_ref) DO UPDATE SET ai_title=excluded.ai_title,` +
          ` ai_desc=excluded.ai_desc, ai_checked=excluded.ai_checked`
      ).bind(ref, title, desc, now, now).run();
    })
  );
  return { processed: pending.results.length, ok };
}
