// Local one-shot seeder.
//
//   npm run seed:fetch     -> hits Overpass, writes scripts/seed-osm.sql
//   npm run seed:local     -> applies that SQL to the local D1
//   npm run seed:remote    -> applies it to the remote D1
//
// Kept as a SQL-file step (rather than writing to D1 directly) so you can eyeball
// the data before it lands, and re-apply idempotently via the upsert below.

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { fetchOsmPlaces } from "../src/lib/overpass.mjs";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "seed-osm.sql");

const q = (v) => (v == null ? "NULL" : `'${String(v).replace(/'/g, "''")}'`);

function upsert(p) {
  return (
    `INSERT INTO osm_places ` +
    `(osm_id,name,category,lat,lng,has_water,has_dump,has_toilets,fee,tags,updated_at) VALUES (` +
    [
      q(p.osm_id),
      q(p.name),
      q(p.category),
      p.lat,
      p.lng,
      p.has_water,
      p.has_dump,
      p.has_toilets,
      q(p.fee),
      q(p.tags),
      q(p.updated_at),
    ].join(",") +
    `) ON CONFLICT(osm_id) DO UPDATE SET ` +
    `name=excluded.name,category=excluded.category,lat=excluded.lat,lng=excluded.lng,` +
    `has_water=excluded.has_water,has_dump=excluded.has_dump,has_toilets=excluded.has_toilets,` +
    `fee=excluded.fee,tags=excluded.tags,updated_at=excluded.updated_at;`
  );
}

console.log("Fetching UK extract from Overpass (can take ~30-90s)...");
const places = await fetchOsmPlaces();

const counts = places.reduce((m, p) => ((m[p.category] = (m[p.category] || 0) + 1), m), {});
console.log(`Got ${places.length} places:`, counts);

const sql =
  "-- Generated by scripts/seed.mjs — OSM data © OpenStreetMap contributors (ODbL).\n" +
  "BEGIN TRANSACTION;\n" +
  places.map(upsert).join("\n") +
  "\nCOMMIT;\n";

await writeFile(OUT, sql);
console.log(`Wrote ${OUT}. Now run: npm run seed:local  (or seed:remote)`);
